=== dmsm2000/PEI/BuyTeck_validation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
    xmlns:seller="http://www.buyteck.com/seller"
    xmlns:product="http://www.buyteck.com/product">
    
    <xs:import schemaLocation="seller.xsd" namespace="http://www.buyteck.com/seller" />
    <xs:import schemaLocation="product.xsd" namespace="http://www.buyteck.com/product" />

    <xs:element name="DOCUMENT">
        <xs:complexType>
            <xs:all>
                <!-- SELLER INICIO -->
                <xs:element name="SELLER">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="UID" type="xs:integer" maxOccurs="1"></xs:element>
                            <xs:element name="NAME" type="xs:string" maxOccurs="1"></xs:element>
                            <xs:element name="NIF" maxOccurs="1" >
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="([1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9])"></xs:pattern>
                                        <xs:minLength value="9"/>
                                        <xs:maxLength value="9"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="CONTACTS">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="PHONE" maxOccurs="1" >
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="([1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9])"></xs:pattern>
                                                    <xs:minLength value="9"/>
                                                    <xs:maxLength value="9"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="EMAIL" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*"></xs:pattern>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            
                            <!-- ADDRESS INICIO -->
                            
                            <xs:element name="ADDRESS">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="NUMBER" type="xs:integer" maxOccurs="1" />
                                        <xs:element name="STREET" type="xs:string" maxOccurs="1"/>
                                        <xs:element name="POSTAL_CODE" maxOccurs="1">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:pattern value="([1-9][0-9][0-9][0-9])-([0-9][0-9][0-9])"></xs:pattern>
                                                    <xs:minLength value="8"/>
                                                    <xs:maxLength value="8"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="CITY" type="xs:string" maxOccurs="1" />
                                        <xs:element name="COUNTRY" type="xs:string" maxOccurs="1" />
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>  
                        
                            <!-- ADDRESS FIM -->
                            
                        </xs:all>
                    </xs:complexType>
                </xs:element>
                <!-- SELLER FIM -->
                
                <xs:element name="PRODUCTS">
                    <xs:complexType>
                        <xs:sequence>
                            
                            <!-- Inicio product -->
                            
                            <xs:element name="PRODUCT" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        
                                        <!-- Inicio product info -->
                                        <xs:element name="PRODUCT_INFO" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="NAME" type="xs:string" minOccurs="1"></xs:element>
                                                    <xs:element name="DESCRIPTION" type="xs:string" minOccurs="1"></xs:element>
                                                    <xs:element name="BRAND" type="xs:string" minOccurs="1"></xs:element>
                                                    <xs:element name="STOCK" type="xs:integer" minOccurs="0"></xs:element>
                                                    <xs:element name="PRICE" type="xs:float" minOccurs="0"></xs:element>
                                                    <xs:element name="MODEL" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:all>
                                                                <xs:element name="NAME" type="xs:string"></xs:element>
                                                            </xs:all>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="KEY_CHARACTERISTICS" minOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="CHARACTERISTIC" type="xs:string" maxOccurs="unbounded"></xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:all>
                                            </xs:complexType>
                                        </xs:element>
                                        <!-- fim product info -->
                                        
                                        <!-- inicio sale info -->
                                        <xs:element name="SALE_INFO" minOccurs="1" maxOccurs="1">
                                            <xs:complexType>
                                                <xs:all>
                                                    <xs:element name="ID" type="xs:integer" minOccurs="1" maxOccurs="1"></xs:element>
                                                    <xs:element name="MIN_BID" type="xs:float" minOccurs="0" maxOccurs="1"></xs:element>
                                                    <xs:element name="STARTING_PRICE" type="xs:float" minOccurs="0" maxOccurs="1"></xs:element>
                                                    <xs:element name="BUY_NOW" type="xs:float" minOccurs="0" maxOccurs="1"></xs:element>
                                                    <xs:element name="START_DATE" type="xs:date" minOccurs="1" maxOccurs="1"></xs:element>
                                                    <xs:element name="END_DATE" type="xs:date" minOccurs="1" maxOccurs="1"></xs:element>
                                                    <xs:element name="AVAILABLE_COUNTRYS">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="COUNTRY" type="xs:string" maxOccurs="unbounded"></xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="PAYMENT_METHODS">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="PAYMENT_METHOD" type="xs:string" maxOccurs="unbounded"></xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:all>
                                                <xs:attribute name="type">
                                                    <xs:simpleType>
                                                        <xs:restriction base="xs:string">
                                                            <xs:enumeration value="direct selling"></xs:enumeration>
                                                            <xs:enumeration value="auction"></xs:enumeration>
                                                        </xs:restriction>
                                                    </xs:simpleType>
                                                </xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                        <!-- fim sale info -->
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            
                            <!-- fim product -->
                            
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
            <xs:attribute name="date" type="xs:date"></xs:attribute>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== dmsm2000/PEI/empresaTeste.xml
<?xml version="1.0" encoding="UTF-8"?>
<DOCUMENT date="2020-06-01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="buyTeck_validation.xsd"
    xmlns:s="http://www.buyteck.com/seller"
    xmlns:a="http://www.buyteck.com/address"
    xmlns:p="http://www.buyteck.com/product"
    xmlns:pi="http://www.buyteck.com/productinfo"
    xmlns:si="http://www.buyteck.com/saleinfo"> <!--date: Data de criação do documento-->
    <s:SELLER> <!-- Toda a informação referente ao vendedor -->
        <UID>01</UID> <!-- Código de vendedor valor inteiro incremental -->
        <NAME>Exemplo</NAME>
        <NIF>123456789</NIF> <!-- Verificar que é um NIF válido (9 números) --> 
        <CONTACTS>
            <PHONE>999888777</PHONE> <!-- Verificar que é um número de tlf válido -->
            <EMAIL>exemplo@gmail.com</EMAIL> <!-- Verificar condições para ser um email -->
        </CONTACTS>
        <a:ADDRESS>
            <STREET>Rua de exemplo</STREET>
            <CITY>Cidade de Exemplo</CITY>
            <COUNTRY>País de exemplo</COUNTRY> 
            <POSTAL_CODE>4000-765</POSTAL_CODE>
            <NUMBER>01</NUMBER>
        </a:ADDRESS> 
    </s:SELLER>
    
    <PRODUCTS> <!-- Todos os produtos disponíveis -->
        
        <!-- Produto 1 -->
        <p:PRODUCT>
            <pi:PRODUCT_INFO>
                <NAME>Produto de exemplo 01</NAME> <!-- obrigatorio -->
                <DESCRIPTION>Eu sou um produto de exemplo</DESCRIPTION> <!-- obrigatorio -->
                <BRAND>Marca de exemplo</BRAND> <!-- obrigatorio -->
                <STOCK>10</STOCK> <!-- default = 1 -->
                <MODEL> <!-- Se aplicável -->
                    <NAME>Modelo 1</NAME> <!-- obrigatorio -->
                </MODEL>
                <KEY_CHARACTERISTICS> <!-- obrigatorio -->
                    <CHARACTERISTIC>
                        Característica 01
                    </CHARACTERISTIC>
                    <CHARACTERISTIC>
                        Característica 02
                    </CHARACTERISTIC>
                </KEY_CHARACTERISTICS> 
            </pi:PRODUCT_INFO>
            
            <si:SALE_INFO type="direct selling" status="ativo">
                <ID>01</ID>
                <START_DATE>2020-11-11</START_DATE>
                <END_DATE>2020-11-11</END_DATE>
                <PRICE>1.8</PRICE>
                <AVAILABLE_COUNTRYS>    
                    <COUNTRY>Angola</COUNTRY>
                    <COUNTRY>Portugal</COUNTRY>
                </AVAILABLE_COUNTRYS>
                <PAYMENT_METHODS>
                    <PAYMENT_METHOD>PAYPALL</PAYMENT_METHOD>
                    <PAYMENT_METHOD>MBWAY</PAYMENT_METHOD>
                    <PAYMENT_METHOD>CREDIT CARD</PAYMENT_METHOD>
                </PAYMENT_METHODS>
            </si:SALE_INFO>
        </p:PRODUCT>
        
        <!-- Produto 2 -->
        <p:PRODUCT>
            <pi:PRODUCT_INFO>
                <NAME>Produto de exemplo 02</NAME>
                <DESCRIPTION>Eu sou um produto de exemplo</DESCRIPTION>
                <BRAND>Marca de exemplo</BRAND>
                <KEY_CHARACTERISTICS> 
                    <CHARACTERISTIC>
                        Característica 01
                    </CHARACTERISTIC>
                    <CHARACTERISTIC>
                        Característica 02
                    </CHARACTERISTIC>
                </KEY_CHARACTERISTICS> 
            </pi:PRODUCT_INFO>
            
            <si:SALE_INFO type="auction" status="inativo">
                <ID>01</ID>
                <MIN_BID>10</MIN_BID> <!-- Incremento mínimo -->
                <STARTING_PRICE>12</STARTING_PRICE> <!-- Preço base -->
                <BUY_NOW>100</BUY_NOW> <!-- Se aplicável, valor de compra instantânea -->
                <START_DATE>2020-11-11</START_DATE>
                <END_DATE>2020-11-11</END_DATE>
                <AVAILABLE_COUNTRYS>
                    <COUNTRY>Angola</COUNTRY>
                    <COUNTRY>Portugal</COUNTRY>
                </AVAILABLE_COUNTRYS>
                <PAYMENT_METHODS>
                    <PAYMENT_METHOD>PAYPALL</PAYMENT_METHOD>
                </PAYMENT_METHODS>
            </si:SALE_INFO>
        </p:PRODUCT>
        
    </PRODUCTS>
</DOCUMENT>

=== dmsm2000/PEI/testeSeller.xml
<?xml version="1.0" encoding="UTF-8"?>
<DOCUMENT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="BuyTeck_validation.xsd" date="2020-01-02"> <!--date: Data de criação do documento-->
    <SELLER> <!-- Toda a informação referente ao vendedor -->
        <UID>01</UID> <!-- Código de vendedor valor inteiro incremental -->
        <NAME>Exemplo</NAME>
        <NIF>12345678</NIF> <!-- Verificar que é um NIF válido (9 números) -->
        <CONTACTS>
            <PHONE>999888777</PHONE> <!-- Verificar que é um número de tlf válido -->
            <EMAIL>exemplo@gmail.com</EMAIL> <!-- Verificar condições para ser um email -->
        </CONTACTS>
        <ADDRESS>
            <STREET>Rua de exemplo</STREET>
            <CITY>Cidade de Exemplo</CITY>
            <COUNTRY>País de exemplo</COUNTRY> 
            <POSTAL_CODE>4000-765</POSTAL_CODE>
            <NUMBER>01</NUMBER>
        </ADDRESS>
    </SELLER>
</DOCUMENT>
